config/routes.rb
Rails.application.routes.draw do
  resources :factors
  resources :questions
  resources :analyses
  root to: 'pages#home'
  get '/sitemap', to: 'pages#sitemap'
  get '/sitemap.xml', :to => 'pages#sitemap', :defaults => {:format => 'xml'}
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  before_action :set_analysis, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:new, :edit, :update, :destroy]

  def authenticate_admin
    redirect_to '/', alert: 'Not authorized.' unless current_user && access_whitelist
  end

  # GET /analyses
  # GET /analyses.json
  def index
    @analyses = Analysis.all
  end

  # GET /analyses/1
  # GET /analyses/1.json
  def show
    @analysis =  Analysis.friendly.find(params[:id])
  end

  # GET /analyses/new
  def new
    @analysis = Analysis.new
  end

  # GET /analyses/1/edit
  def edit
  end

  # POST /analyses
  # POST /analyses.json
  def create
    @analysis = Analysis.new(analysis_params)

    respond_to do |format|
      if @analysis.save
        format.html { redirect_to @analysis, notice: 'Analysis was successfully created.' }
        format.json { render :show, status: :created, location: @analysis }
      else
        format.html { render :new }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analyses/1
  # PATCH/PUT /analyses/1.json
  def update
    respond_to do |format|
      if @analysis.update(analysis_params)
        format.html { redirect_to @analysis, notice: 'Analysis was successfully updated.' }
        format.json { render :show, status: :ok, location: @analysis }
      else
        format.html { render :edit }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analyses/1
  # DELETE /analyses/1.json
  def destroy
    @analysis.destroy
    respond_to do |format|
      format.html { redirect_to analyses_url, notice: 'Analysis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analysis
      @analysis = Analysis.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def analysis_params
      params.require(:analysis).permit(:seo_title, :seo_meta_description, :analysis_article_image, :analysis_article_title, :introduction, :title1, :image_link1, :affiliate_link1, :summary1, :highlight1_1_short, :highlight1_2_short, :highlight1_3_short, :highlight1_1, :highlight1_2, :highlight1_3, :highlight1_4, :highlight1_5, :synopsis1, :title2, :image_link2, :affiliate_link2, :summary2, :highlight2_1_short, :highlight2_2_short, :highlight2_3_short, :highlight2_1, :highlight2_2, :highlight2_3, :highlight2_4, :highlight2_5, :synopsis2, :title3, :image_link3, :affiliate_link3, :summary3, :highlight3_1_short, :highlight3_2_short, :highlight3_3_short, :highlight3_1, :highlight3_2, :highlight3_3, :highlight3_4, :highlight3_5, :synopsis3, :title4, :image_link4, :affiliate_link4, :summary4, :highlight4_1, :highlight4_2, :highlight4_3, :highlight4_4, :highlight4_5, :synopsis4, :title5, :image_link5, :affiliate_link5, :summary5, :highlight5_1, :highlight5_2, :highlight5_3, :highlight5_4, :highlight5_5, :synopsis5, :title6, :image_link6, :affiliate_link6, :summary6, :highlight6_1, :highlight6_2, :highlight6_3, :highlight6_4, :highlight6_5, :synopsis6, :title7, :image_link7, :affiliate_link7, :summary7, :highlight7_1, :highlight7_2, :highlight7_3, :highlight7_4, :highlight7_5, :synopsis7, :title8, :image_link8, :affiliate_link8, :summary8, :highlight8_1, :highlight8_2, :highlight8_3, :highlight8_4, :highlight8_5, :synopsis8, :title9, :image_link9, :affiliate_link9, :summary9, :highlight9_1, :highlight9_2, :highlight9_3, :highlight9_4, :highlight9_5, :synopsis9, :title10, :image_link10, :affiliate_link10, :summary10, :highlight10_1, :highlight10_2, :highlight10_3, :highlight10_4, :highlight10_5, :synopsis10, :buyers_guide, :expert_tip, :did_you_know, :conclusion)
    end

    def access_whitelist
      current_user.try(:admin?) || current_user.try(:door_super?)
    end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/views/analyses/_form.html.erb
<%= form_with(model: analysis, local: true) do |form| %>
  <% if analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analysis.errors.count, "error") %> prohibited this analysis from being saved:</h2>

      <ul>
        <% analysis.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seo_title %>
    <%= form.text_area :seo_title %>
  </div>

  <div class="field">
    <%= form.label :seo_meta_description %>
    <%= form.text_area :seo_meta_description %>
  </div>

  <div class="field">
    <%= form.label :analysis_article_image %>
    <%= form.text_area :analysis_article_image %>
  </div>

  <div class="field">
    <%= form.label :analysis_article_title %>
    <%= form.text_area :analysis_article_title %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :title1 %>
    <%= form.text_area :title1 %>
  </div>

  <div class="field">
    <%= form.label :image_link1 %>
    <%= form.text_area :image_link1 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link1 %>
    <%= form.text_area :affiliate_link1 %>
  </div>

  <div class="field">
    <%= form.label :summary1 %>
    <%= form.text_area :summary1 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_1_short %>
    <%= form.text_area :highlight1_1_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_2_short %>
    <%= form.text_area :highlight1_2_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_3_short %>
    <%= form.text_area :highlight1_3_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_1 %>
    <%= form.text_area :highlight1_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_2 %>
    <%= form.text_area :highlight1_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_3 %>
    <%= form.text_area :highlight1_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_4 %>
    <%= form.text_area :highlight1_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight1_5 %>
    <%= form.text_area :highlight1_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis1 %>
    <%= form.text_area :synopsis1 %>
  </div>

  <div class="field">
    <%= form.label :title2 %>
    <%= form.text_area :title2 %>
  </div>

  <div class="field">
    <%= form.label :image_link2 %>
    <%= form.text_area :image_link2 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link2 %>
    <%= form.text_area :affiliate_link2 %>
  </div>

  <div class="field">
    <%= form.label :summary2 %>
    <%= form.text_area :summary2 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_1_short %>
    <%= form.text_area :highlight2_1_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_2_short %>
    <%= form.text_area :highlight2_2_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_3_short %>
    <%= form.text_area :highlight2_3_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_1 %>
    <%= form.text_area :highlight2_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_2 %>
    <%= form.text_area :highlight2_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_3 %>
    <%= form.text_area :highlight2_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_4 %>
    <%= form.text_area :highlight2_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight2_5 %>
    <%= form.text_area :highlight2_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis2 %>
    <%= form.text_area :synopsis2 %>
  </div>

  <div class="field">
    <%= form.label :title3 %>
    <%= form.text_area :title3 %>
  </div>

  <div class="field">
    <%= form.label :image_link3 %>
    <%= form.text_area :image_link3 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link3 %>
    <%= form.text_area :affiliate_link3 %>
  </div>

  <div class="field">
    <%= form.label :summary3 %>
    <%= form.text_area :summary3 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_1_short %>
    <%= form.text_area :highlight3_1_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_2_short %>
    <%= form.text_area :highlight3_2_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_3_short %>
    <%= form.text_area :highlight3_3_short, :maxlength => 35 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_1 %>
    <%= form.text_area :highlight3_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_2 %>
    <%= form.text_area :highlight3_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_3 %>
    <%= form.text_area :highlight3_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_4 %>
    <%= form.text_area :highlight3_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight3_5 %>
    <%= form.text_area :highlight3_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis3 %>
    <%= form.text_area :synopsis3 %>
  </div>

  <div class="field">
    <%= form.label :title4 %>
    <%= form.text_area :title4 %>
  </div>

  <div class="field">
    <%= form.label :image_link4 %>
    <%= form.text_area :image_link4 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link4 %>
    <%= form.text_area :affiliate_link4 %>
  </div>

  <div class="field">
    <%= form.label :summary4 %>
    <%= form.text_area :summary4 %>
  </div>

  <div class="field">
    <%= form.label :highlight4_1 %>
    <%= form.text_area :highlight4_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight4_2 %>
    <%= form.text_area :highlight4_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight4_3 %>
    <%= form.text_area :highlight4_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight4_4 %>
    <%= form.text_area :highlight4_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight4_5 %>
    <%= form.text_area :highlight4_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis4 %>
    <%= form.text_area :synopsis4 %>
  </div>

  <div class="field">
    <%= form.label :title5 %>
    <%= form.text_area :title5 %>
  </div>

  <div class="field">
    <%= form.label :image_link5 %>
    <%= form.text_area :image_link5 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link5 %>
    <%= form.text_area :affiliate_link5 %>
  </div>

  <div class="field">
    <%= form.label :summary5 %>
    <%= form.text_area :summary5 %>
  </div>

  <div class="field">
    <%= form.label :highlight5_1 %>
    <%= form.text_area :highlight5_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight5_2 %>
    <%= form.text_area :highlight5_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight5_3 %>
    <%= form.text_area :highlight5_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight5_4 %>
    <%= form.text_area :highlight5_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight5_5 %>
    <%= form.text_area :highlight5_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis5 %>
    <%= form.text_area :synopsis5 %>
  </div>

  <div class="field">
    <%= form.label :title6 %>
    <%= form.text_area :title6 %>
  </div>

  <div class="field">
    <%= form.label :image_link6 %>
    <%= form.text_area :image_link6 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link6 %>
    <%= form.text_area :affiliate_link6 %>
  </div>

  <div class="field">
    <%= form.label :summary6 %>
    <%= form.text_area :summary6 %>
  </div>

  <div class="field">
    <%= form.label :highlight6_1 %>
    <%= form.text_area :highlight6_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight6_2 %>
    <%= form.text_area :highlight6_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight6_3 %>
    <%= form.text_area :highlight6_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight6_4 %>
    <%= form.text_area :highlight6_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight6_5 %>
    <%= form.text_area :highlight6_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis6 %>
    <%= form.text_area :synopsis6 %>
  </div>

  <div class="field">
    <%= form.label :title7 %>
    <%= form.text_area :title7 %>
  </div>

  <div class="field">
    <%= form.label :image_link7 %>
    <%= form.text_area :image_link7 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link7 %>
    <%= form.text_area :affiliate_link7 %>
  </div>

  <div class="field">
    <%= form.label :summary7 %>
    <%= form.text_area :summary7 %>
  </div>

  <div class="field">
    <%= form.label :highlight7_1 %>
    <%= form.text_area :highlight7_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight7_2 %>
    <%= form.text_area :highlight7_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight7_3 %>
    <%= form.text_area :highlight7_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight7_4 %>
    <%= form.text_area :highlight7_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight7_5 %>
    <%= form.text_area :highlight7_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis7 %>
    <%= form.text_area :synopsis7 %>
  </div>

  <div class="field">
    <%= form.label :title8 %>
    <%= form.text_area :title8 %>
  </div>

  <div class="field">
    <%= form.label :image_link8 %>
    <%= form.text_area :image_link8 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link8 %>
    <%= form.text_area :affiliate_link8 %>
  </div>

  <div class="field">
    <%= form.label :summary8 %>
    <%= form.text_area :summary8 %>
  </div>

  <div class="field">
    <%= form.label :highlight8_1 %>
    <%= form.text_area :highlight8_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight8_2 %>
    <%= form.text_area :highlight8_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight8_3 %>
    <%= form.text_area :highlight8_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight8_4 %>
    <%= form.text_area :highlight8_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight8_5 %>
    <%= form.text_area :highlight8_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis8 %>
    <%= form.text_area :synopsis8 %>
  </div>

  <div class="field">
    <%= form.label :title9 %>
    <%= form.text_area :title9 %>
  </div>

  <div class="field">
    <%= form.label :image_link9 %>
    <%= form.text_area :image_link9 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link9 %>
    <%= form.text_area :affiliate_link9 %>
  </div>

  <div class="field">
    <%= form.label :summary9 %>
    <%= form.text_area :summary9 %>
  </div>

  <div class="field">
    <%= form.label :highlight9_1 %>
    <%= form.text_area :highlight9_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight9_2 %>
    <%= form.text_area :highlight9_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight9_3 %>
    <%= form.text_area :highlight9_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight9_4 %>
    <%= form.text_area :highlight9_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight9_5 %>
    <%= form.text_area :highlight9_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis9 %>
    <%= form.text_area :synopsis9 %>
  </div>

  <div class="field">
    <%= form.label :title10 %>
    <%= form.text_area :title10 %>
  </div>

  <div class="field">
    <%= form.label :image_link10 %>
    <%= form.text_area :image_link10 %>
  </div>

  <div class="field">
    <%= form.label :affiliate_link10 %>
    <%= form.text_area :affiliate_link10 %>
  </div>

  <div class="field">
    <%= form.label :summary10 %>
    <%= form.text_area :summary10 %>
  </div>

  <div class="field">
    <%= form.label :highlight10_1 %>
    <%= form.text_area :highlight10_1 %>
  </div>

  <div class="field">
    <%= form.label :highlight10_2 %>
    <%= form.text_area :highlight10_2 %>
  </div>

  <div class="field">
    <%= form.label :highlight10_3 %>
    <%= form.text_area :highlight10_3 %>
  </div>

  <div class="field">
    <%= form.label :highlight10_4 %>
    <%= form.text_area :highlight10_4 %>
  </div>

  <div class="field">
    <%= form.label :highlight10_5 %>
    <%= form.text_area :highlight10_5 %>
  </div>

  <div class="field">
    <%= form.label :synopsis10 %>
    <%= form.text_area :synopsis10 %>
  </div>

  <div class="field">
    <%= form.label :buyers_guide %>
    <%= form.text_area :buyers_guide %>
  </div>

  <div class="field">
    <%= form.label :expert_tip %>
    <%= form.text_area :expert_tip %>
  </div>

  <div class="field">
    <%= form.label :did_you_know %>
    <%= form.text_area :did_you_know %>
  </div>

  <div class="field">
    <%= form.label :conclusion %>
    <%= form.text_area :conclusion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/analyses/edit.html.erb
<h1>Editing Analysis</h1>

<%= render 'form', analysis: @analysis %>

<%= link_to 'Show', @analysis %> |
<%= link_to 'Back', analyses_path %>

app/views/analyses/new.html.erb
<h1>New Analysis</h1>

<%= render 'form', analysis: @analysis %>

<%= link_to 'Back', analyses_path %>