config/routes.rb
Rails.application.routes.draw do
  resources :factors
  resources :questions
  resources :analyses
  root to: 'pages#home'
  get '/sitemap', to: 'pages#sitemap'
  get '/sitemap.xml', :to => 'pages#sitemap', :defaults => {:format => 'xml'}
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/factor.rb
class Factor < ApplicationRecord
  belongs_to :analysis
end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController
  before_action :set_factor, only: [:show, :edit, :update, :destroy]

  # GET /factors
  # GET /factors.json
  def index
    @factors = Factor.all
  end

  # GET /factors/1
  # GET /factors/1.json
  def show
  end

  # GET /factors/new
  def new
    @factor = Factor.new
  end

  # GET /factors/1/edit
  def edit
  end

  # POST /factors
  # POST /factors.json
  def create
    @factor = Factor.new(factor_params)

    respond_to do |format|
      if @factor.save
        format.html { redirect_to @factor, notice: 'Factor was successfully created.' }
        format.json { render :show, status: :created, location: @factor }
      else
        format.html { render :new }
        format.json { render json: @factor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factors/1
  # PATCH/PUT /factors/1.json
  def update
    respond_to do |format|
      if @factor.update(factor_params)
        format.html { redirect_to @factor, notice: 'Factor was successfully updated.' }
        format.json { render :show, status: :ok, location: @factor }
      else
        format.html { render :edit }
        format.json { render json: @factor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factors/1
  # DELETE /factors/1.json
  def destroy
    @factor.destroy
    respond_to do |format|
      format.html { redirect_to factors_url, notice: 'Factor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factor
      @factor = Factor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def factor_params
      params.require(:factor).permit(:title, :body, :analysis_id)
    end
end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/views/factors/_form.html.erb
<%= form_with(model: factor, local: true) do |form| %>
  <% if factor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(factor.errors.count, "error") %> prohibited this factor from being saved:</h2>

      <ul>
        <% factor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :analysis_id %>
    <%= form.text_field :analysis_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/factors/edit.html.erb
<h1>Editing Factor</h1>

<%= render 'form', factor: @factor %>

<%= link_to 'Show', @factor %> |
<%= link_to 'Back', factors_path %>

app/views/factors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Factors</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Analysis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @factors.each do |factor| %>
      <tr>
        <td><%= factor.title %></td>
        <td><%= factor.body %></td>
        <td><%= factor.analysis_id %></td>
        <td><%= link_to 'Show', factor %></td>
        <td><%= link_to 'Edit', edit_factor_path(factor) %></td>
        <td><%= link_to 'Destroy', factor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Factor', new_factor_path %>

app/views/factors/new.html.erb
<h1>New Factor</h1>

<%= render 'form', factor: @factor %>

<%= link_to 'Back', factors_path %>

app/views/factors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @factor.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @factor.body %>
</p>

<p>
  <strong>Analysis:</strong>
  <%= @factor.analysis_id %>
</p>

<%= link_to 'Edit', edit_factor_path(@factor) %> |
<%= link_to 'Back', factors_path %>